apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iris-classifier-models-pvc
  labels:
    app: iris-classifier
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
